version: "2.4"
services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_HOST}/nzbget:/config
      - ${DATA_HOST}/usenet:/data/usenet
    ports:
      - 6789:6789

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_HOST}/sonarr:/config
      - ${DATA_HOST}:/data
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_HOST}/radarr:/config
      - ${DATA_HOST}:/data
    ports:
      - 7878:7878

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_HOST}/bazarr:/config
      - ${DATA_HOST}/media/movies:/movies
      - ${DATA_HOST}/media/tv:/tv
    ports:
      - 6767:6767

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_HOST}/jellyfin:/config
      - ${DATA_HOST}/media:/data
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # required for hardware acceleration

networks:
  medianet:
    driver: bridge
    # Need static IPs for network for Synology firewall
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
