version: "2.4"
services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN # required to modify network interfaces
    networks:
      - medianet
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=combustion
    volumes:
      - ${HOST}/docker/transmission/:/data/transmission-home
      - ${HOST}/data/torrents/completed/:/data/completed
      - ${HOST}/data/torrents/incomplete/:/data/incomplete
      - ${HOST}/data/torrents/watch/:/data/watch
    ports:
      - 9091:9091
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/jackett:/config
    ports:
      - 9117:9117

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/nzbget:/config
      - ${HOST}/data/usenet:/data/usenet
    ports:
      - 6789:6789

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/sonarr:/config
      - ${HOST}/data:/data
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/radarr:/config
      - ${HOST}/data:/data
    ports:
      - 7878:7878

  ombi:
    container_name: ombi
    image: linuxserver/ombi:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/ombi:/config
    ports:
      - 3579:3579

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/docker/heimdall:/config
    ports:
      - 9292:80
      - 9393:443

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    networks:
      - medianet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST}/data/media/movies:/data/movies
      - ${HOST}/data/media/tv:/data/tvshows
      - ${HOST}/docker/jellyfin:/config
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri

networks:
  medianet:
    driver: bridge
